### ISSUE TITLE
Failed to open RocksDB Error due to Soace

### ISSUE THREAD

**Issue by andela-anandaa** [instructure/canvas-data-loader#10]
### Description ###
The script has been running okay, but recently, we started getting this error, here is the full log:

```
INFO 2018-08-23T11:55:28Z: cdl_runner: Setting up API Client...
INFO 2018-08-23T11:55:28Z: cdl_runner: Connecting to RocksDB Store....
thread 'main' panicked at 'Failed to open RocksDB: Error { message: "IO error: No space left on deviceWhile appending to file: /tmp/cdl-rocksdb/000302.sst: No space left on device" }', /checkout/src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

We increased the disk space but still getting the same error.

**Comment by SecurityInsanity** [comment]
Hello,

Do you perhaps have multiple drives and increased the storage space of the incorrect one? The "RocksDB" Store is stored in: `/tmp` which is generally part of the root drive, as opposed to where we store downloaded files which you specify in your config.

A: `df -h` should show you if any drives are full specifically the root drive.

**Comment by andela-anandaa** [comment]
Thanks @SecurityInsanity ! Looks like after restart, now the script can run but fails at the DB connection, this is unrelated but just incase you have any pointers:
```
INFO 2018-08-24T09:34:10Z: cdl_runner: Connecting to the DB
thread 'main' panicked at 'Failed to turn connection into pool. This should never happen: InitializationError(None)', /checkout/src/libcore/result.rs:916:5
```
cc. @andela-joladimeji

**Comment by andela-anandaa** [comment]
// issue resolved though, as-is, will close it soon.
